// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATS3ZMR1K0ipsal7cxtCNp5_a0pUx7QOY',
    appId: '1:589011325156:web:952774e841254e1f7c5cf1',
    messagingSenderId: '589011325156',
    projectId: 'fizz-4c8c7',
    authDomain: 'fizz-4c8c7.firebaseapp.com',
    storageBucket: 'fizz-4c8c7.appspot.com',
    measurementId: 'G-M64ZHFH9GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBqo1Aaon2P8cgYSbYUyXcwCPU4rcziU',
    appId: '1:589011325156:android:6a84387f497b91767c5cf1',
    messagingSenderId: '589011325156',
    projectId: 'fizz-4c8c7',
    storageBucket: 'fizz-4c8c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGJ496ga24ti7q6i6roS3asLPogrZVas',
    appId: '1:589011325156:ios:24a18c577b7906177c5cf1',
    messagingSenderId: '589011325156',
    projectId: 'fizz-4c8c7',
    storageBucket: 'fizz-4c8c7.appspot.com',
    androidClientId:
        '589011325156-27eeun09vppona8t6870s5k1vt766m62.apps.googleusercontent.com',
    iosClientId:
        '589011325156-66svrcgdqdgvfv50ik9b7hk94dk4f591.apps.googleusercontent.com',
    iosBundleId: 'com.example.fizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGJ496ga24ti7q6i6roS3asLPogrZVas',
    appId: '1:589011325156:ios:24a18c577b7906177c5cf1',
    messagingSenderId: '589011325156',
    projectId: 'fizz-4c8c7',
    storageBucket: 'fizz-4c8c7.appspot.com',
    androidClientId:
        '589011325156-27eeun09vppona8t6870s5k1vt766m62.apps.googleusercontent.com',
    iosClientId:
        '589011325156-66svrcgdqdgvfv50ik9b7hk94dk4f591.apps.googleusercontent.com',
    iosBundleId: 'com.example.fizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATS3ZMR1K0ipsal7cxtCNp5_a0pUx7QOY',
    appId: '1:589011325156:web:64c8f1ab69fa950d7c5cf1',
    messagingSenderId: '589011325156',
    projectId: 'fizz-4c8c7',
    authDomain: 'fizz-4c8c7.firebaseapp.com',
    storageBucket: 'fizz-4c8c7.appspot.com',
    measurementId: 'G-B5D8K8PPN2',
  );
}
